/* You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t. */

var findTheDifference = function(s, t) {
    s = s.split("").sort()
    t = t.split("").sort()
    return t.filter((x,i) => x !== s[i])[0] 
};

console.log(findTheDifference("acb", "aacb"))